version: '3.8'

services:
  app:
    build: .
    container_name: rascafull-crm
    restart: unless-stopped
    ports:
      - "8484:8484"
      - "8485:8485"
    env_file:
      - .env
    environment:
      - PORT=8484
      - HEADLESS=true
    volumes:
      - ./:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./sessions:/app/sessions
      - ./bot_1:/app/bot_1
      - ./bot_2:/app/bot_2
      - ./bot_3:/app/bot_3
