version: '3.8'

services:
  app:
    build: .
    container_name: rascafull-crm
    restart: unless-stopped
    ports:
      - "8484:8484"
      - "8485:8485"
    env_file:
      - .env
    environment:
      - PORT=8484
      - HEADLESS=true
      - BACKEND_URL=http://127.0.0.1:8484
    volumes:
      - ./logs:/app/logs
      - ./sessions:/app/sessions
      - ./bot_1:/app/bot_1
      - /app/bot_1/node_modules
      - ./bot_2:/app/bot_2
      - /app/bot_2/node_modules
      - ./bot_3:/app/bot_3
      - /app/bot_3/node_modules
      - ./bot_4:/app/bot_4
      - /app/bot_4/node_modules
    shm_size: '2gb'
