version: '3.8'

services:
  app:
    build: .
    container_name: rascafull-crm
    restart: unless-stopped
    ports:
      - "8484:8484"
      - "8485:8485"
    env_file:
      - .env
    environment:
      - PORT=8484
      - HEADLESS=true
    volumes:
      - ./bot_2/sessions:/app/bot_2/sessions
      - ./logs:/app/logs
